branches:
  only:
  - master

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    env: SWIFT_SNAPSHOT=4.0.3
  - os: linux
    dist: trusty
    sudo: required
  - os: osx
    osx_image: xcode9.3
    sudo: required
    env: SWIFT_SNAPSHOT=swift-4.1-RELEASE
  - os: osx
    osx_image: xcode9.2
    sudo: required
    env: SWIFT_SNAPSHOT=swift-4.0.3-RELEASE
before_install:
- git clone https://github.com/IBM-Swift/Package-Builder.git
script:
- ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
